### PR TITLE
Fix Error for math.random(low#,high#) requirement

### PR DESCRIPTION
**Pull request by jcfrosty**
Fix Error for math.random(low#,high#) requirement

### CODE REVIEW

**Comment by D00Med** [comment]
Again? :S I thought I'd fixed it all. It's certainly fixed on the update branch. 
Also why are you getting this error? It's important to find out because this error will mess up situations with two variables inside the function:
math.random(variable,variable2)
Where either number could be larger than the other.

**Comment by jcfrosty** [comment]
Lua 5.1 limitation possibly?

**Comment by D00Med** [comment]
Hm, sorry to ask again, but which version of minetest are you using? and where did you get it? (as in, is it a custom build or something?)

**Comment by jcfrosty** [comment]
minetest version 4.17
Not a custom build, its from a Sabayon Repository. Sabayon is based on
Gentoo which uses ebuilds. ebuilds basically pull source code directly from
approved source (typically originator) and compile/install. Sabayon does
this action, but packages it in prebuilt form and places them into a
repository for downloads/installs/updates.

**Comment by D00Med** [comment]
Hmm, so I guess you can't use the downloads from the minetest website?

**Comment by jcfrosty** [comment]
Thats exactly what Gentoo uses. it downloads the source from the minetest
website and compiles it.

**Comment by D00Med** [comment]
You haven't had this problem with any other mods or subgames, have you?

**Comment by jcfrosty** [comment]
Haven't really tried any other mods/subgames. I did try just the original
minetest game with no issues.

**Comment by D00Med** [comment]
And there's no way your version could be compiled wrong?

**Comment by jcfrosty** [comment]
Nope, afraid not. the normal minetest game runs just fine.

**Comment by D00Med** [comment]
Can you have a go with another mod or subgame? like mobs redo?
That way we'd know where the problem is.

**Comment by jcfrosty** [comment]
sure. I'll test it and let you know what happens.

**Comment by D00Med** [comment]
Thanks

**Comment by jcfrosty** [comment]
OK, I've tested Regnum-3.2.9 . Not sure I understand the point of that game, but OK. It only had one issue with the music loading mod, after i removed that one plugin, Game ran smooth, no other issues.

I figured it could be my version of lua so I upgraded to 5.3.3 from 5.1, no change.
So I tried recompiling and installing minetest 4.7.1, no change.

All the errors I get are the same errors no matter what I do.

**Comment by mckaygerhard** [comment]
> OK, I've tested Regnum-3.2.9 . Not sure I understand the point of that game, but OK. It only had one issue with the music loading mod, after i removed that one plugin, Game ran smooth, no other issues.
> 
> I figured it could be my version of lua so I upgraded to 5.3.3 from 5.1, no change. So I tried recompiling and installing minetest 4.7.1, no change.
> 
> All the errors I get are the same errors no matter what I do.

this change was already integrated since #39 was merged!  related commits are 
* commit 5e4e39edda614a8a9bf86d35a66678206f0d6e12
* commit acf7cd29f07e2986908dc691e197c957b9543f86

**Pull request closed without merging**
