### PR TITLE
Update init.lua

### PR DESCRIPTION
**Pull request by jcfrosty**
Same problem with order of lower#,higher# when using random function.

### CODE REVIEW

**Comment by D00Med** [comment]
Thankyou for this. I won't merge just yet because I still don't know enough about the problem.

**Comment by jcfrosty** [comment]
if you have hangouts, I can let you know what the issue is. its just a simple switching of the high and low numbers when using math.random(). so for example it says #2 is invalid when using math.random(-25,-30) because -30 is actually a lower number than -25. so it should be math.random(-30,-25). For some reason this cause the game to not even run on my son's desktop while using lua 5.1.3 . Switching them around fixed it.

**Comment by D00Med** [comment]
I understand the idea, but I have never had this problem before, I have been playing the game for months without encountering this problem, and I need to make sure it's not something to do with minetest's version or something else.

I just tested this:
`minetest.register_on_generated(function(minp, maxp)
	minetest.chat_send_all(math.random(-10,-30))
	end)`
And it works fine. But it did also work with the numbers swapped.
This afternoon I will have a look at swapping the numbers around in the subgame anyway, I guess it's likely to be broken if the number placement becomes fixed in future versions.

**Comment by D00Med** [comment]
Thankyou very much for these PR's

**Pull request merged**
